name: Pipeline DeliveryTech

on:
push:
branches: [ "main" ]

jobs:
ci:
runs-on: ubuntu-latest

steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Simular Build
    run: echo "Build realizado com sucesso!"

  - name: Simular Testes
    run: echo "Todos os testes passaram!"

deploy-dev:
runs-on: ubuntu-latest
needs: ci

steps:
  - name: Deploy DEV
    run: echo "Deploy em DEV realizado!"

deploy-staging:
runs-on: ubuntu-latest
needs: deploy-dev

steps:
  - name: Deploy STAGING
    run: echo "Deploy em STAGING realizado!"

deploy-prod:
runs-on: ubuntu-latest
needs: deploy-staging

steps:
  - name: Deploy PRODUÇÃO
    run: echo "Deploy em PRODUÇÃO realizado!"
